---
namespace: jiholland
name: vxlan_evpn
version: 24.2.1
readme: README.md

authors:
  - Jørn Ivar Holland

description: This collection includes helpful Ansible roles and content to help with Cisco VXLAN-EVPN automation.

license:
  - BSD-3-Clause

tags:
  - bgp
  - cisco
  - evpn
  - networking
  - nexus
  - ospf
  - pim
  - vpc
  - vxlan

dependencies:
  cisco.nxos: ">=5.2.1"

repository: https://github.com/jiholland/ansible-collection_vxlan_evpn
issues: https://github.com/jiholland/ansible-collection_vxlan_evpn/issues

build_ignore: []
