objects:
  role:
    dci:
      description: null
      name: dci
      version_added: null
    host_segments:
      description: null
      name: host_segments
      version_added: null
    overlay:
      description: null
      name: overlay
      version_added: null
    underlay:
      description: null
      name: underlay
      version_added: null
    verify:
      description: null
      name: verify
      version_added: null
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module: {}
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 24.2.2
