---
galaxy_info:
  role_name: underlay
  author: Jørn Ivar Holland
  description: Configure underlay network for VXLAN with EVPN controller in multisite clos-network.
  license: BSD-3-Clause
  min_ansible_version: '2.15'
  platforms:
    - name: NXOS
      versions:
        - all
  galaxy_tags:
    - networking
    - cisco
    - nexus
    - clos
    - ospf
    - pim
    - bgp
    - vxlan
    - evpn


dependencies: []
