---
# Argument specification file for dci

argument_specs:
  main:
    options:

      dci_network_role:
        type: str
        choices:
          - border-leaf

      dci_dci_if:
        type: str
        default: loopback100

      dci_dci_ip:
        description: Multi-site interface vip vtep ip.
        type: str
        required: true

      dci_dci_interfaces:
        description: The dci facing interfaces connecting border-leafs to border-leafs across each pod.
        type: list
        required: true
        elements: dict

      dci_bgp_asn:
        description: BGP ASN for underlay and overlay.
        type: int
        required: true

      dci_rid_if:
        type: str
        default: loopback0

      dci_rid_ip:
        type: str
        required: true

      dci_fabric_interfaces:
        description: The fabric facing interfaces connecting spines to border-leafs.
        type: list
        required: true
        elements: dict

      dci_underlay_bgp_neighbors:
        description: BGP underlay neighbors.
        type: list
        required: true
        elements: dict

      dci_overlay_bgp_neighbors:
        description: BGP overlay neighbors.
        type: list
        required: true
        elements: dict

      dci_macsec_key_algorithm:
        type: str
        choices:
          - AES_128_CMAC
          - AES_256_CMAC

      dci_macsec_key_string:
        type: str
        required: true
