---
# tasks file for overlay

- name: Include role specific tasks.
  ansible.builtin.include_tasks:
    file: leaf.yml
  when: overlay_network_role is ansible.builtin.search('leaf')

- name: Include role specific tasks.
  ansible.builtin.include_tasks:
    file: spine.yml
  when: overlay_network_role is eq('spine')
