---
- name: Build VXLAN-EVPN fabric.
  gather_facts: false
  hosts: "{{ target }}"
  roles:
    - role: jiholland.vxlan_evpn.vpc
      when: vpc_domain is defined
      tags:
        - vpc
    - role: jiholland.vxlan_evpn.underlay
      tags:
        - underlay
    - role: jiholland.vxlan_evpn.overlay
      tags:
        - overlay
    - role: jiholland.vxlan_evpn.dci
      when: dci_network_role is eq('border-leaf')
      tags:
        - dci
    - role: jiholland.vxlan_evpn.host_segments
      when: host_segments_network_role is ansible.builtin.search('leaf')
      tags:
        - host_segments
    - role: jiholland.vxlan_evpn.verify
      tags:
        - verify
